# Sudo Code - Keywords
Team Members: Zhu Hanming, Tan Jin, Cao Wenjie, Noel Mathew Isaac

Our submission for Round 1.

In [2]:
import pandas as pd

In [3]:
## Reading in csv file
keyword_df = pd.read_csv('Keyword_spam_question.csv')
keyword_df.head(10)

   index                                               name
0      0        IZRA Cotton Milky Gray Blouse + Skirt Putih
1      1        (Coral Red) IZRA BOUTIQUE Baju Kurung Moden
2      2              (Red) IZRA BOUTIQUE Baju Kurung Moden
3      3  (Peach) IZRA BOUTIQUE Baju Kurung Moden With P...
4      4            (Black) IZRA BOUTIQUE Baju Kurung Moden
5      5                    [Single]Single Air Bed Mattress
6      6        2- in-1  Air Bed Mattress With Sleeping Bag
7      7        [Single] Inflatable Single Air Bed Mattress
8      8            [Double] Easigo Double Air Bed Mattress
9      9        [Double] Inflatable Double Air Bed Mattress

In [4]:
keyword_df.head(30)

    index                                               name
0       0        IZRA Cotton Milky Gray Blouse + Skirt Putih
1       1        (Coral Red) IZRA BOUTIQUE Baju Kurung Moden
2       2              (Red) IZRA BOUTIQUE Baju Kurung Moden
3       3  (Peach) IZRA BOUTIQUE Baju Kurung Moden With P...
4       4            (Black) IZRA BOUTIQUE Baju Kurung Moden
5       5                    [Single]Single Air Bed Mattress
6       6        2- in-1  Air Bed Mattress With Sleeping Bag
7       7        [Single] Inflatable Single Air Bed Mattress
8       8            [Double] Easigo Double Air Bed Mattress
9       9        [Double] Inflatable Double Air Bed Mattress
10     10       High Raise Inflatable Queen Air Bed Mattress
11     11      [Single] Color-Splash Air Bed Single Mattress
12     12                     6ft Aquarium 3 Rings Kids Pool
13     13  IInflatable 2In1 Air Camping Bed Mattress Mat ...
14     14               Jilong inflatable Air Arm Chair Sofa
15     15            ThJilong inflatable Air Side Chair Sofa
16     16  ðŸ”¥âœ”READY STOKâœ”ðŸ”¥Portable Handheld Car Vacuum Cle...
17     17     JILONG Multifunctional Inflatable Air Sofa Bed
18     18        Suuntooo jam tangan berjenama digital watch
19     19  Pulse Sports Watch with Heart Rate Monitor and...
20     20  Adjustable Laptop Table Foldable Notebook Tabl...
21     21  A Bathing Ape Bape Canvas Shoulder Handbag Tot...
22     22  Casual Men Black Jeans / Male Blue Straight Cu...
23     23            IZRA Baju kurung Sutera Cotton in Brown
24     24                         Bikini Type Lingerie (Set)
25     25  Stealth Plane Aircraft Bomber Sports LED Digit...
26     26  Pulse Sports Watch with Heart Rate Monitor and...
27     27  CESARE BLISTER Car Fragrance (set of 2) by Mr ...
28     28                           Balaclava Warm Face Mask
29     29  (Original Microsoft) Xbox 360 Wireless Control...

In [5]:
## Reading in categories
categories_df = pd.read_csv('Extra Material 2 - keyword list_with substring.csv')

In [6]:
## Preparing categories into a dictionary
categories_df.head()
categories = categories_df['Keywords'].tolist()

In [ ]:
categories

## Split each string into a list
cleaned = []
for cat in categories:
    to_append = cat.split(', ')
    cleaned.append(to_append)

## Map each list to their group no. in a dictionary
final_categories = {}
for i in range(len(cleaned)):
    final_categories[i] = cleaned[i]

In [8]:
## Finding out the longest category name - no longer used
longest_string = 0
for k, v in final_categories.items():
    for item in v:
        curr = len(item.split(' '))
        if len(item.split(' ')) >longest_string:
            longest_string = curr
print(longest_string)

5

In [10]:
import nltk
import re
import itertools

## imported itertools originally but ended up unused

In [16]:
## Filter for words and spaces - mistake here: need to keep numbers and '-'
pattern = re.compile('([^\s\w]|_)+')
def clean_names(title):
    title = pattern.sub('', title)
    title = title.lower()
    title = title.strip()
    return title

In [17]:
## Apply cleaning function to df
keyword_df['cleaned_step_1'] = keyword_df['name'].apply(clean_names)

In [18]:
keyword_df.head()

,index,name,cleaned_step_1
0,0,IZRA Cotton Milky Gray Blouse + Skirt Putih,izra cotton milky gray blouse skirt putih
1,1,(Coral Red) IZRA BOUTIQUE Baju Kurung Moden,coral red izra boutique baju kurung moden
2,2,(Red) IZRA BOUTIQUE Baju Kurung Moden,red izra boutique baju kurung moden
3,3,(Peach) IZRA BOUTIQUE Baju Kurung Moden With P...,peach izra boutique baju kurung moden with pat...
4,4,(Black) IZRA BOUTIQUE Baju Kurung Moden,black izra boutique baju kurung moden

In [46]:
## Function to identify matched group numbers
def checker(entry):
    matched_words = {} ## To keep track of all words matched
    to_delete = [] 
    for key, value in final_categories.items():
        for item in value:
            if item in entry:
                to_append = True
                for k in matched_words:
                    if k==item:
                        to_append = False ## We keep the smaller index, which was already found
                    elif k in item:
                        to_delete.append(k) ## If there's a substring already matched, delete it later
                    elif item in k:
                        to_append = False ## Else if we are currently processing a substring, throw it away
                if to_append:
                    matched_words[item] = key ## Add it if it passes the above checks
    result = []
    for item in to_delete:
        if item in matched_words:
            del matched_words[item] ## Remove substrings
    for key, value in matched_words.items():
        if not value in result:
            result.append(value) ## Reduce into a list
    result.sort() 
    return result

In [47]:
## Check the df
keyword_df["final"] = keyword_df["cleaned_step_1"].apply(checker)

In [48]:
keyword_df.head(20)

,index,name,cleaned_step_1,final
0,0,IZRA Cotton Milky Gray Blouse + Skirt Putih,izra cotton milky gray blouse skirt putih,"[31, 33]"
1,1,(Coral Red) IZRA BOUTIQUE Baju Kurung Moden,coral red izra boutique baju kurung moden,[23]
2,2,(Red) IZRA BOUTIQUE Baju Kurung Moden,red izra boutique baju kurung moden,[23]
3,3,(Peach) IZRA BOUTIQUE Baju Kurung Moden With P...,peach izra boutique baju kurung moden with pat...,[23]
4,4,(Black) IZRA BOUTIQUE Baju Kurung Moden,black izra boutique baju kurung moden,[23]
5,5,[Single]Single Air Bed Mattress,singlesingle air bed mattress,"[161, 169]"
6,6,2- in-1 Air Bed Mattress With Sleeping Bag,2 in1 air bed mattress with sleeping bag,"[107, 161, 169]"
7,7,[Single] Inflatable Single Air Bed Mattress,single inflatable single air bed mattress,"[161, 169, 172]"
8,8,[Double] Easigo Double Air Bed Mattress,double easigo double air bed mattress,"[161, 169]"
9,9,[Double] Inflatable Double Air Bed Mattress,double inflatable double air bed mattress,"[161, 169, 172]"
10,10,High Raise Inflatable Queen Air Bed Mattress,high raise inflatable queen air bed mattress,"[161, 169, 172]"
11,11,[Single] Color-Splash Air Bed Single Mattress,single colorsplash air bed single mattress,"[161, 169]"
12,12,6ft Aquarium 3 Rings Kids Pool,6ft aquarium 3 rings kids pool,[231]
13,13,IInflatable 2In1 Air Camping Bed Mattress Mat ...,iinflatable 2in1 air camping bed mattress mat ...,"[161, 169, 170, 172]"
14,14,Jilong inflatable Air Arm Chair Sofa,jilong inflatable air arm chair sofa,"[170, 172]"
15,15,ThJilong inflatable Air Side Chair Sofa,thjilong inflatable air side chair sofa,"[170, 172]"
16,16,ðŸ”¥âœ”READY STOKâœ”ðŸ”¥Portable Handheld Car Vacuum Cle...,ready stokportable handheld car vacuum cleaner...,"[172, 274, 275]"
17,17,JILONG Multifunctional Inflatable Air Sofa Bed,jilong multifunctional inflatable air sofa bed,[172]
18,18,Suuntooo jam tangan berjenama digital watch,suuntooo jam tangan berjenama digital watch,"[132, 239]"
19,19,Pulse Sports Watch with Heart Rate Monitor and...,pulse sports watch with heart rate monitor and...,"[74, 132]"

In [50]:
## Export the results
new_df = keyword_df[["index", "final"]]
new_df.columns=['index','groups_found']
new_df.to_csv("solution.csv", index=False)